### ISSUE TITLE
zones_on_point does not respect scrollable position

### ISSUE THREAD

**Issue by zeptofine** [jhannyj/iced_drop#3]
In this video I show a drag and dropped list working perfectly all the way up to the point where a scrollable starts to.. scroll. After this, the zones seem to be sticking to the top of the list. Whenever i drop things, it is added to the relative point at the top of the list, shown by the [n] on the debug output.

Video has audio narration

https://github.com/jhannyj/iced_drop/assets/54873330/40ae852c-30e5-466e-9752-be8d9cae5e05

**Comment by zeptofine** [comment]
I've made a branch which fixes it for my usecase, but it is not thoroughly tested and it relies on the default filter in zones_on_point https://github.com/zeptofine/iced_drop/tree/offset_scrollables

**Comment by jhannyj** [comment]
Merged your solution
